try:
    print(x)
except:
    print("An exception occurres")
